### ISSUE TITLE
ebs-csi-driver addon: IAM error when creating PVC from snapshot

### ISSUE THREAD

**Issue by netiperher** [awslabs/cdk-eks-blueprints#1151]
### Describe the bug

When using the official `EbsCsiDriverAddOn` together with the snapshot-controller addon (currently not included in blueprints) and trying to create a PVC from snapshot. Then the pvc ends up in error state due to missing IAM permissions.

### Expected Behavior

PVC to be created without errors.

### Current Behavior

When describing the pvc it has the following error:

```
PersistentVolumeClaim/my-data-0    failed to provision volume with StorageClass "gp3": rpc error: code = Internal desc = Could not create volume "pvc-87ad104a-5ee1-4912-8375-0e249a68c51c": could not create volume in EC2: operation error EC2: CreateVolume, https response error StatusCode: 403, RequestID: <request id>, api error UnauthorizedOperation: You are not authorized to perform this operation. User: arn:aws:sts::<aws id>:assumed-role/MyCluster-ebscsicontrollersasaRole1BBC-207DLV5Q89A5/1747307062150341641 is not authorized to perform: ec2:CreateVolume
```

### Reproduction Steps

when trying to create the following PVC:

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-data-0
spec:
  accessModes:
  - ReadWriteOnce
  dataSource:
    apiGroup: snapshot.storage.k8s.io
    kind: VolumeSnapshot
    name: my-data-0-snapshot
  resources:
    requests:
      storage: 50Gi
  storageClassName: gp3
  volumeMode: Filesystem
  volumeName: pvc-87ad104a-5ee1-4912-8375-0e249a68c51c
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Gi
  phase: Bound
```

### Possible Solution

According to official documentation in https://docs.aws.amazon.com/eks/latest/userguide/ebs-csi.html, the aws-ebs-csi-driver should create role with the built-in `AmazonEBSCSIDriverPolicy` policy.

The `EbsCsiDriverAddOn` currently uses a custom IAM policy which is **not** identical 
https://github.com/awslabs/cdk-eks-blueprints/blob/main/lib/addons/ebs-csi-driver/iam-policy.ts

Manually adding the `AmazonEBSCSIDriverPolicy` policy to the role resulted in the pvc to be created successfully. 

### CDK CLI Version

~2.162.0

### EKS Blueprints Version

~1.16.2

### Node.js Version

v22.11.0

### Environment details (OS name and version, etc.)

Linux
